import prop1 from "../assets/marketplace/prop1.svg";
import prop3 from "../assets/marketplace/prop3.svg";
import prop5 from "../assets/marketplace/prop5.svg";
import prop6 from "../assets/marketplace/prop6.svg";
import prop4 from "../assets/marketplace/prop4.svg";
import desc1 from "../assets/marketplace/description1.svg";

const propertyData = [
  {
    id: 1,
    name: "GeoLandmark Zone, Epe 6",
    location: "Epe, Lagos",
    availableUnits: 10,
    price: "₦1,000,000",
    img: prop1,
    ownership: "Co-ownership",
    coOwners: "10",
    type: "Land",
    soldOut: false,
    category: "Basic",
    descImg: [
      desc1,
      desc1,
      desc1,
      desc1,
      desc1,
      desc1,
      desc1,
      desc1,
      desc1,
      desc1,
    ],
    details:
      "GoeLandmark is pleased to announce a very rewarding and exciting co-ownership opportunity at GeoLandmark Zone, Epe V, a 650sqm wide expanse of land located in Ilara, Epe. This property is what you will call favored, as it is positioned right in the epicenter of an intending boom that's building up rapidly with each passing day. It is generally considered every investor’s heart delight because it is projected to grow exponentially at an average of 30% per annum.GoeLandmark is pleased to announce a very rewarding and exciting co-ownership opportunity at GeoLandmark Zone, Epe V, a 650sqm wide expanse of land located in Ilara, Epe. This property is what you will call favored, as it is positioned right in the epicenter of an intending boom that's building up rapidly with each passing day. It is generally considered every investor’s heart delight because it is projected to grow exponentially at an average of 30% per annum.",
  },
  {
    id: 2,
    name: "GeoLandmark UK Living 1",
    location: "Manchester, UK",
    availableUnits: 6,
    price: "£1,250",
    img: prop3,
    ownership: "Co-ownership",
    coOwners: "10",
    type: "Rental",
    soldOut: false,
    category: "Premium",
    descImg: [
      prop3,
      prop3,
      prop3,
      prop3,
      prop3,
      prop3,
      prop3,
      prop3,
      prop3,
      prop3,
    ],
    details:
      "GoeLandmark is pleased to announce a very rewarding and exciting co-ownership opportunity at GeoLandmark Zone, Epe V, a 650sqm wide expanse of land located in Ilara, Epe. This property is what you will call favored, as it is positioned right in the epicenter of an intending boom that's building up rapidly with each passing day. It is generally considered every investor’s heart delight because it is projected to grow exponentially at an average of 30% per annum.GoeLandmark is pleased to announce a very rewarding and exciting co-ownership opportunity at GeoLandmark Zone, Epe V, a 650sqm wide expanse of land located in Ilara, Epe. This property is what you will call favored, as it is positioned right in the epicenter of an intending boom that's building up rapidly with each passing day. It is generally considered every investor’s heart delight because it is projected to grow exponentially at an average of 30% per annum.",
  },
  {
    id: 3,
    name: "GeoLandmark Zone, Epe 7",
    location: "Epe, Lagos",
    availableUnits: 0,
    price: "₦1,000,000",
    img: prop5,
    ownership: "private",
    coOwners: null,
    type: "Land",
    soldOut: true,
    category: "Classic",
    descImg: [prop5, prop5, prop5, prop5, prop5, prop5, prop5, prop5, prop5],
    details:
      "GoeLandmark is pleased to announce a very rewarding and exciting co-ownership opportunity at GeoLandmark Zone, Epe V, a 650sqm wide expanse of land located in Ilara, Epe. This property is what you will call favored, as it is positioned right in the epicenter of an intending boom that's building up rapidly with each passing day. It is generally considered every investor’s heart delight because it is projected to grow exponentially at an average of 30% per annum.GoeLandmark is pleased to announce a very rewarding and exciting co-ownership opportunity at GeoLandmark Zone, Epe V, a 650sqm wide expanse of land located in Ilara, Epe. This property is what you will call favored, as it is positioned right in the epicenter of an intending boom that's building up rapidly with each passing day. It is generally considered every investor’s heart delight because it is projected to grow exponentially at an average of 30% per annum.",
  },

  {
    id: 4,
    name: "GeoLandmark Zone, Epe 2",
    location: "Epe, Lagos",
    availableUnits: 135,
    price: "₦35,000",
    img: prop4,
    ownership: "Co-ownership",
    coOwners: "6",
    type: "Land",
    soldOut: false,
    category: "Basic",
    descImg: [
      prop4,
      prop4,
      prop4,
      prop4,
      prop4,
      prop4,
      prop4,
      prop4,
      prop4,
      prop4,
    ],
    details:
      "GoeLandmark is pleased to announce a very rewarding and exciting co-ownership opportunity at GeoLandmark Zone, Epe V, a 650sqm wide expanse of land located in Ilara, Epe. This property is what you will call favored, as it is positioned right in the epicenter of an intending boom that's building up rapidly with each passing day. It is generally considered every investor’s heart delight because it is projected to grow exponentially at an average of 30% per annum.GoeLandmark is pleased to announce a very rewarding and exciting co-ownership opportunity at GeoLandmark Zone, Epe V, a 650sqm wide expanse of land located in Ilara, Epe. This property is what you will call favored, as it is positioned right in the epicenter of an intending boom that's building up rapidly with each passing day. It is generally considered every investor’s heart delight because it is projected to grow exponentially at an average of 30% per annum.",
  },
  {
    id: 5,
    name: "GeoLandmark Zone, Epe 2",
    location: "Epe, Lagos",
    availableUnits: 135,
    price: "₦35,000",
    img: prop6,
    ownership: "private",
    coOwners: "6",
    type: "Rental",
    soldOut: false,
    category: "Premium",
    descImg: [
      prop6,
      prop6,
      prop6,
      prop6,
      prop6,
      prop6,
      prop6,
      prop6,
      prop6,
      prop6,
    ],
    details:
      "GoeLandmark is pleased to announce a very rewarding and exciting co-ownership opportunity at GeoLandmark Zone, Epe V, a 650sqm wide expanse of land located in Ilara, Epe. This property is what you will call favored, as it is positioned right in the epicenter of an intending boom that's building up rapidly with each passing day. It is generally considered every investor’s heart delight because it is projected to grow exponentially at an average of 30% per annum.GoeLandmark is pleased to announce a very rewarding and exciting co-ownership opportunity at GeoLandmark Zone, Epe V, a 650sqm wide expanse of land located in Ilara, Epe. This property is what you will call favored, as it is positioned right in the epicenter of an intending boom that's building up rapidly with each passing day. It is generally considered every investor’s heart delight because it is projected to grow exponentially at an average of 30% per annum.",
  },
  {
    id: 6,
    name: "GeoLandmark Zone, UK Living 2",
    location: "Oxford, UK",
    availableUnits: 0,
    price: "£3,250",
    img: prop4,
    ownership: "Co-ownership",
    coOwners: "6",
    type: "Apartment",
    soldOut: true,
    category: "Classic",
    descImg: [
      prop4,
      prop4,
      prop4,
      prop4,
      prop4,
      prop4,
      prop4,
      prop4,
      prop4,
      prop4,
    ],
    details:
      "GeoLandmark is pleased to announce a very rewarding and exciting co-ownership opportunity at GeoLandmark Zone, Epe V, a 650sqm wide expanse of land located in Ilara, Epe. This property is what you will call favored, as it is positioned right in the epicenter of an intending boom that's building up rapidly with each passing day. It is generally considered every investor’s heart delight because it is projected to grow exponentially at an average of 30% per annum. \n GeoLandmark is pleased to announce a very rewarding and exciting co-ownership opportunity at GeoLandmark Zone, Epe V, a 650sqm wide expanse of land located in Ilara, Epe. This property is what you will call favored, as it is positioned right in the epicenter of an intending boom that's building up rapidly with each passing day. It is generally considered every investor’s heart delight because it is projected to grow exponentially at an average of 30% per annum.",
  },
];

export default propertyData;
